name: LC-Dailies

on:
  schedule:
    - cron: "0 0 * * *" # Daily Leetcode question updates daily at UTC midnight (https://crontab.guru/#0_0_*_*_*)
  workflow_dispatch: # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run script
        run: deno task start
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
