name: cf push

on:
  push:
    branches: [main]

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [canary]

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Push to Cloudflare
        run: deno task cf:push
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
