name: dnt

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: Run build script
        run: deno task dnt $GITHUB_SHA

      - name: Checkout new branch for npm/ content
        run: |
          git checkout -B npm || git checkout npm
          git rm -rf .
          cp -r npm/* .
          rm -rf npm
          git config --global user.email "me@example.com"
          git config --global user.name "LC-Dailies Bot"
          git add .
          git commit -m "Publish npm ✨"

      - name: Push new branch to remote
        run: |
          # Replace with the appropriate remote repository URL
          # Example: git push --force origin npm
          git push --force -u origin npm
